---
services:
  valheim:
    image: indifferentbroccoli/valheim-server-docker:latest
    restart: unless-stopped
    container_name: valheim
    stop_grace_period: 30s
    ports:
      - '2456:2456/udp'
      - '2457:2457/udp'
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - .env.example
    volumes:
      - ./valheim/server-files:/valheim
      - ./valheim/server-data:/valheim-saves
